### ISSUE TITLE
working on it

### ISSUE THREAD

**Issue by TheMowgliMan** [TheMowgliMan/Country-Clash#14]
Um, 3qc, your changes completely broke it on my system. I was pulling your new commits, and many things that were needed for it to run were missing, and some proper code was reverted. You need to revert it immediately.

**Comment by 3quarterscolon** [comment]
I'M TRYING

**Comment by 3quarterscolon** [comment]
I DON'T KNOW WHAT HAPPENED

**Comment by 3quarterscolon** [comment]
I'm so sorry.

**Comment by 3quarterscolon** [comment]
Those weren't the things I was trying to change. I tried to pull the code from main, and then there were merge conflicts, and when I was trying to fix them I must've accidentally pushed to main. I'm sorry.

**Comment by 3quarterscolon** [comment]
Is this fixed?: https://github.com/3quarterscolon/Country-Clash/tree/fix-it

**Comment by TheMowgliMan** [comment]
Sorry, I wanted to make sure you saw it. Most likely these:

- You added back Node2D as the root for the main menu. I suspect you didn't merge main back into your fork.
- You added back the hack that I removed, probably for the same reason as above.
- A signal from the buttons was broken. I suspect that is the biggest offender



> I'm so sorry.

It's okay. You wouldn't BELIEVE the number of music projects and coding projects I've messed up like this

> Those weren't the things I was trying to change. I tried to pull the code from main, and then there were merge conflicts, and when I was trying to fix them I must've accidentally pushed to main. I'm sorry.

That sounds like something I might do someday....

> Is this fixed?: https://github.com/3quarterscolon/Country-Clash/tree/fix-it

I'll look.

**Comment by 3quarterscolon** [comment]
> Sorry, I wanted to make sure you saw it. Most likely these:
> 
> * You added back Node2D as the root for the main menu. I suspect you didn't merge main back into your fork.
> * You added back the hack that I removed, probably for the same reason as above.
> * A signal from the buttons was broken. I suspect that is the biggest offender
> 
> > I'm so sorry.
> 
> It's okay. You wouldn't BELIEVE the number of music projects and coding projects I've messed up like this
> 
> > Those weren't the things I was trying to change. I tried to pull the code from main, and then there were merge conflicts, and when I was trying to fix them I must've accidentally pushed to main. I'm sorry.
> 
> That sounds like something I might do someday....
> 
> > Is this fixed?: https://github.com/3quarterscolon/Country-Clash/tree/fix-it
> 
> I'll look.

And of course, my revert has merge conflicts or something, so who knows if it's actually fixed.

**Comment by TheMowgliMan** [comment]
FIXED!!!!!!!!! I'll merge it in.

**Comment by TheMowgliMan** [comment]
11 minutes of total panic. What a day.

**Comment by 3quarterscolon** [comment]
Wait, are cities fixed?

**Comment by TheMowgliMan** [comment]
Cities were being added in. So there is some unfinished code, but it isn't doing anything. The main problems were in the main menu, there were cross-fork-merge shenanigans. It was a Frankenstein of a scene, with some of your stuff and some of mine both added in.

**Comment by 3quarterscolon** [comment]
Okay

**Comment by TheMowgliMan** [comment]
Your merges deleted the city texture, which isn't taht surprising, and it did nothing wrong.
