### ISSUE TITLE
Add latitude color variation

### ISSUE THREAD

**Issue by 3quarterscolon** [TheMowgliMan/Country-Clash#24]
Lighter colors further north and south and darker colors closer to the equator to make it look like it’s colder near the poles.

This isn’t necessary or anything, but I think it might be a nice substitute for actually calculating climate. Shouldn’t be too hard to implement.

**Comment by 3quarterscolon** [comment]
It's a tad bit more complex than I thought.

![Screen Shot 2022-05-28 at 9 06 08 PM](https://user-images.githubusercontent.com/94267030/170847766-e8dba21e-6438-4a74-a936-d38d9c9bfabb.png)

**Comment by 3quarterscolon** [comment]
Now when I open the map I get this error:
`"cmd.get_type() != Variant::STRING" is true.`
what does that even mean???

**Comment by 3quarterscolon** [comment]
Dozens of attempts later, and I still have no idea how to get this to work properly. I can get tantalizingly close, but for some reason the last step always results in it failing.

**Comment by 3quarterscolon** [comment]
I guess I'll try again tomorrow.

Here's the closest I can get:
![Screen Shot 2022-05-28 at 9 58 57 PM](https://user-images.githubusercontent.com/94267030/170848887-a70bce3f-697b-47c0-93dc-2d642edc669e.png)

(note: right now I'm just debugging it to find a function to get the distance from the "equator". in the final version, that would be used to shade the biomes.)

**Comment by TheMowgliMan** [comment]
Likely some dust code. That error means that there was supposed to be a
command there but it didn't consist of text.

**Comment by 3quarterscolon** [comment]
> Likely some dust code. That error means that there was supposed to be a command there but it didn't consist of text.
> […](#)

I solved it after I posted that comment. I think it was caused by accidental division by zero.

**Comment by TheMowgliMan** [comment]
Hmmm... It would say division by zero error. I suspect you accidentally
tried to call something like "42a(3)", or that general structure.

**Comment by 3quarterscolon** [comment]
> Hmmm... It would say division by zero error. I suspect you accidentally tried to call something like "42a(3)", or that general structure.
> […](#)

I don’t know what that is, but I don’t think that’s what I did.

**Comment by 3quarterscolon** [comment]
Still not working at all.
![Uploading Screen Shot 2022-05-29 at 8.47.37 PM.png…]()

**Comment by 3quarterscolon** [comment]
NOTHING IS WORKING AAAAAAAA
I CAN'T EVEN GET AN IF FUNCTION TO DO ANYTHING WHAT IS HAPPENING

**Comment by 3quarterscolon** [comment]
now it's slightly less crazy in terms of color
![Screen Shot 2022-05-29 at 9 08 30 PM](https://user-images.githubusercontent.com/94267030/170900103-925928e0-890f-4521-9e14-c6ad6d433dbd.png)
I see this as a total win

**Comment by 3quarterscolon** [comment]
one step forward, 300 steps back.
![Uploading Screen Shot 2022-05-29 at 9.15.15 PM.png…]()

**Comment by 3quarterscolon** [comment]
I- what?
![Screen Shot 2022-05-29 at 9 17 32 PM](https://user-images.githubusercontent.com/94267030/170900643-65f74e0b-021c-4015-b389-26c8d9e8e032.png)

**Comment by 3quarterscolon** [comment]
The return of shading
![Screen Shot 2022-05-29 at 9 19 42 PM](https://user-images.githubusercontent.com/94267030/170900766-c29e9258-977d-46f2-b1d7-d0180d7f676e.png)
So I've come full-circle and I still haven't been able to do the thing I wanted to in the first place.

**Comment by 3quarterscolon** [comment]
...and we're back to this.
![Screen Shot 2022-05-29 at 9 25 19 PM](https://user-images.githubusercontent.com/94267030/170901123-53f753d7-e07f-4ed1-a275-6f24e5fdb8ef.png)

**Comment by 3quarterscolon** [comment]
And back to being shadingless. I'm done for tonight, maybe tomorrow?

**Comment by TheMowgliMan** [comment]
Wow. there is a value that is added to for shading, add to that value in
each: abs((y - (map_size_square / 2)) / 3) . You may need to clamp it. I'll
see if I can get it working.

**Comment by TheMowgliMan** [comment]
You know what? I bet it's value overflow. I'll see if clamping it fixes it.

**Comment by TheMowgliMan** [comment]
Done! I added polar regions for good measure:
![Country Clash- The Game (DEBUG) 5_31_2022 3_09_28 PM](https://user-images.githubusercontent.com/96443213/171292647-3327861a-3d5a-4d4a-abbf-eda6288f88e4.png)

**Comment by 3quarterscolon** [comment]
> Wow. there is a value that is added to for shading, add to that value in each: abs((y - (map_size_square / 2)) / 3) . You may need to clamp it. I'll see if I can get it working.
> […](#)

I tried clamping it, I guess I didn’t do it correctly.
